DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;

CREATE TABLE IF NOT EXISTS users(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    other_user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_map             TEXT DEFAULT '[]',
    other_user_map       TEXT DEFAULT '[]',
    current_turn_user_id BIGINT REFERENCES users(id),  -- NULL = игра ещё не началась
    status               VARCHAR(50) DEFAULT 'LOBBY'
                         CHECK (status IN ('LOBBY', 'PLACING', 'ACTIVE', 'FINISHED')),
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    winner_id            BIGINT,
    CONSTRAINT different_users CHECK (user_id != other_user_id)
);

-- Индексы для ускорения поиска
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_other_user_id ON sessions(other_user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON sessions(status);